config/routes.rb
Integra::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'

  resources :jardines

  match 'materiales/modal/:id' => 'materiales#modal'
  match 'solicitudes/pendientes' => 'solicitudes#pendientes'
  resources :solicitudes, :only => :show

  match '/periodos/:periodo_id/materiales/upload' => 'materiales#upload'

  resources :periodos do
    resources :materiales
    resources :solicitudes, :except => [:show, :new]
  end

  resources :categorias
  match 'solicitudes/xls' => "solicitudes#xls"
  match 'solicitudes/:solicitud_id/aprobar' => 'solicitudes#aprobar'
  match 'solicitudes/:solicitud_id/rechazar' => 'solicitudes#rechazar'
  match 'solicitudes/new/:jardin_id' => "solicitudes#new"
  get 'jardines/:jardin/usuarios' => "usuarios#index"
  delete 'jardines/:jardin/usuarios' => "usuarios#destroy"
  match 'usuarios/upload' => 'usuarios#upload'
  get '/usuarios/:id/edit' => 'usuarios#edit'
  put '/usuarios/:id' => 'usuarios#update'
  get '/usuarios/:jardin_codigo/new' => 'usuarios#new'
  match '/usuarios/:jardin_codigo/edit' => 'usuarios#edit'
  post '/usuarios' => 'usuarios#create'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :sessions

  resources :usuarios


  root :to => 'periodos#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/periodo.rb
# -*- coding: utf-8 -*-
class Periodo < ActiveRecord::Base
  #un periodo es un proceso de carro de compras
  #cada periodo posee una lista de materiales y un presupuesto para cada jardin

  #tipos de periodos:
  #1: Sin autorización regional, jardín posee un propuesta y puede elegir cualquier material.
  #2: Sin autorización regional, jardín sólo puede elegir materiales que pertenecen a su nivel.

  self.table_name =  'periodos'
  attr_accessible :time_start, :time_end, :instrucciones, :nombre, :planilla, :aprobado, :tipo
  has_many :solicitudes, :class_name => 'Solicitud', :dependent => :delete_all
  validates_presence_of :nombre, :time_start, :time_end, :instrucciones, :aprobado, :tipo
  has_many :materiales, :class_name => 'Material', :order => 'categoria_id ASC, producto ASC', :dependent => :delete_all
  has_many :presupuestos, :dependent => :delete_all
  validates_with PeriodoValidator

  mount_uploader :planilla, MaterialesUploader
  mount_uploader :batch, BatchUploader

  def en_plazo?
    return true if Time.now >self.time_start and Time.now < self.time_end
  end

  def time_end=ts
    return if ts.nil?
    write_attribute(:time_end, (Time.parse(ts) + 1.day).midnight - 1.second)
  end

  def self.activos
    p = Periodo.where(:status => 4).order("id asc")
    output = []
    for i in p
      output << i if i.en_plazo?
    end
    return output
  end

  def activo?
    if self.status == 4 and self.en_plazo?
      return true
    else
      return false
    end

  end

  def self.presupuesto_job(periodo_id)
    @periodo = Periodo.find(periodo_id)
    begin
        procesar(@periodo.planilla.url)
    rescue Exception => e
      puts e
      @periodo.status = 7
      @periodo.save!
    end
    Rails.cache.clear
  end

  private
    def procesar(file)
      @periodo.transaction do
        if @periodo.tipo == 1
          procesar_periodo_tipo_1(file)
        elsif @periodo.tipo == 2
          procesar_periodo_tipo_2(file)
        else
          procesar_periodo_tipo_3(file)
        end
      end
    end

    def read_file(file)
      begin
        return Roo::Excelx.new(file)
      rescue TypeError
        return Roo::Excel.new(file)
      end
    end

    def buscaNivelesMateriales(input,row)
      output = []
      #columnas de niveles materiales
      for j in 'G'..'V'
        nivel = input.cell(1,j)
        if !nivel.nil? and nivel.size >= 2 and !nivel.downcase.include? 'precio'  and !nivel.downcase.include? 'presupuesto'
          val = input.cell(row,j)
          if val.to_i > 0
            output << nivel
          end
        end
      end
      return output
    end

    def buscaNivelesJardin(input,row,hoja)
      output = []
      for j in 'F'..'U'
        nivel = input.cell(4,j,hoja)
        if !nivel.nil? and nivel.size >= 2 and !nivel.downcase.include? 'precio'  and !nivel.downcase.include? 'presupuesto'
          val = input.cell(row,j,hoja)
          if val.to_i > 0
            output << nivel
          end
        end
      end
      return output
    end


    def procesar_periodo_tipo_2(file)
      input = read_file(file)
      hojas = input.sheets

      #materiales
      puts 'materiales'
      materiales_id = []
      materiales_count = 0
      precio_en_primera_hoja = false
      columna_precio = nil

      headers = input.row(1)
      for t in 0..(headers.size-1)
        test = headers[t]
        if !test.nil? and test.downcase.include? "precio"
          precio_en_primera_hoja = true
          columna_precio = t+1
        end
      end

      puts "columna precio: #{columna_precio}"


      for i in 2..input.last_row(hojas[0])
        codigo = input.cell(i,'B',hojas[0])
        if codigo.length > 2
          m = Material.where(:periodo_id => @periodo.id, :codigo => codigo).first
          if m.nil?
            m = Material.new
            m.codigo = codigo
            m.periodo_id = @periodo.id
            m.precio_neto = 0
          end
          m.precio_neto = input.cell(i,columna_precio,hojas[0]) if precio_en_primera_hoja
          m.coeficienteTecnico = input.cell(i,'C',hojas[0])
          m.producto = input.cell(i,'D',hojas[0])
          m.caracteristicas = input.cell(i,'E',hojas[0])
          m.unidad = input.cell(i,'F',hojas[0])
          m.categoria_id = Categoria.buscar(input.cell(i,'A',hojas[0])).id
          m.save!
          materiales_count += 1
          MaterialNivel.where(:material_codigo => codigo).delete_all
          niveles = buscaNivelesMateriales(input,i)
          niveles.each do |nivel|
            mn = MaterialNivel.new
            mn.material_codigo = m.codigo
            mn.nivel = nivel
            mn.save!
          end
        end

      end
      min_column = 20+2
      max_column = input.last_column(hojas[1])
      last = 0

      if !precio_en_primera_hoja
        puts "precios de los materiales"
        #precios de los materiales
        precios_count = 0
        for col in min_column..max_column
          codigo = input.cell(3,col,hojas[1])
          if codigo && codigo.size > 1
            precio = input.cell(2,col,hojas[1]).to_f
            m = Material.where(:periodo_id => @periodo.id, :codigo => codigo).first
            throw "Error de integridad" if m.nil?
            m.precio_neto = precio
            m.save!
            precios_count += 1
            last = col
          end
        end
        max_column = last
        raise "error de integridad: precios != materiales " if precios_count != materiales_count
      end

      puts "eliminando la asociacion de jardin nivel"

      JardinNivel.delete_all

      puts "jardines"

      columna_presupuesto = nil

      headers = input.row(4,hojas[1])
      for test in 0..(headers.size-1)
        if headers[test].downcase.include? 'presupuesto'
          columna_presupuesto = test+1
        end
      end

      puts "columna_presupuesto: #{columna_presupuesto}"

      raise 'no se encuentra columna presupuesto' if columna_presupuesto.nil?

      #jardines
      for row in 5..input.last_row(hojas[1])
        codigo = input.cell(row,'C',hojas[1]).to_i

        if codigo && codigo > 0
          puts codigo
          jardin = Jardin.find_by_codigo(codigo)
          if jardin.nil?
            jardin = Jardin.new
            jardin.codigo = codigo
          end
          jardin.nombre = input.cell(row,'D',hojas[1]).capitalize
          jardin.modalidad_atencion = input.cell(row,'E',hojas[1])
          jardin.region = input.cell(row,'A',hojas[1]).to_i
          jardin.comuna = input.cell(row,'B',hojas[1])
          jardin.activo = 1
          jardin.save!


          niveles = buscaNivelesJardin(input,row,hojas[1])
          puts "niveles: #{niveles.join('-')}"
          niveles.each do |nivel|
            jn = JardinNivel.new
            jn.jardin_codigo = jardin.codigo
            jn.nivel = nivel
            jn.save!
          end

          #solicitud
          s = Solicitud.where(:periodo_id => @periodo.id, :jardin_codigo => jardin.codigo).first
          if s.nil?
            puts "creando solicitud jardin_codigo: #{jardin.codigo}, periodo_id: #{@periodo.id}"
            s = Solicitud.new
            s.periodo_id = @periodo.id
            s.jardin_codigo = jardin.codigo
            s.save!
          end
          detalles_ids = []
          for col in min_column..max_column
            codigo = input.cell(3,col,hojas[1])
            m = Material.where(:periodo_id => @periodo.id, :codigo => codigo).first
            detalle = Detalle.where(:solicitud_id => s.id, :material_id => m.id).first
            if detalle.nil?
              detalle = Detalle.new
              detalle.solicitud_id = s.id
              detalle.material_id = m.id
            end
            detalle.cantidad_propuesta = input.cell(row,col,hojas[1]).to_i
            detalle.save!
            puts "detalle para material: #{m.id} solicitud: #{s.id} propuesto: #{detalle.cantidad_propuesta}"
            detalles_ids << detalle.id
          end
          d = Detalle.where(:solicitud_id => s.id)
          if detalles_ids.size > 0
            d = d.where("id not in (?)",detalles_ids)
          end
          d.delete_all


          p = Presupuesto.where(:jardin_id => jardin.id, :periodo_id => @periodo.id).first
          if p.nil?
            p = Presupuesto.new
            p.jardin_id = jardin.id
            p.periodo_id = @periodo.id
          end
          p.presupuesto = input.cell(row,columna_presupuesto,hojas[1])
          p.save!

          puts "presupuesto: #{p.presupuesto}"

        end
      end

      @periodo.status = 4
      @periodo.save!

    end

    def check_if_picture_exists(material_id)
      require 'rest-client'
      begin
        RestClient.head Material.find(material_id).square_image
        puts "imagen existe: #{material_id} -> #{Material.find(material_id).square_image}"
        return true
      rescue
        puts "imagen no existe"
        return false
      end
    end

    def procesar_periodo_tipo_3(file)
      procesar_periodo_tipo_2(file)
    end

    def procesar_periodo_tipo_1(file)
      input = nil
      begin
        input = Roo::Excelx.new(file)
      rescue TypeError
        begin
          begin
            input = Roo::Excel.new(file)
          rescue TypeError
            puts "error al procesar el tipo de archivo"
            @periodo.status = 7
            @periodo.save!
            return
          end
        end
      end
      #materiales
      materiales_id = []
      for i in input.first_column..input.last_column
        if input.cell(1, i).to_f > 0
          codigo = input.cell(2, i).strip.gsub(/\s/, '')
          nombre = input.cell(3, i).strip
          precio = input.cell(1, i).to_f
          m = Material.where(['periodo_id = ? and codigo = ?', @periodo.id, codigo]).first
          if m.nil?
            m = Material.new
            m.codigo = codigo
            m.periodo_id = @periodo.id
          end
          m.producto = nombre
          m.precio_neto = precio

app/controllers/periodos_controller.rb
class PeriodosController < ApplicationController
  before_filter :require_valid_user
  before_filter :admin_permission, :except => [:index, :show]
  before_filter :admin_or_regional_permission, :only => :show

  # GET /periodos
  # GET /periodos.json
  def index

    if (current_user.admin == 0)
      @periodos = Periodo.activos
    else
      @periodos = Periodo.order('id asc')
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @periods }
    end
  end

  def subir_listado_materiales
    puts 'subir_listado_mat'
    puts @uploader.inspect
    @periodo = Periodo.find(params[:id])

  end


  # GET /periodos/1
  # GET /periodos/1.json
  def show
    @periodo = Periodo.find(params[:id])

    puts 'LLEGUE'
    if @periodo.status == 0
      if params[:key]
        @uploader = @periodo.planilla
        @uploader.key = params[:key]
        @periodo.status = 3
        @periodo.save!
        PresupuestoJob.new.async.perform(@periodo.id)
        #Periodo.delay.presupuesto_job(@periodo.id)
        redirect_to periodo_url(@periodo)
      else
	puts 'arribauploader'
        @uploader = @periodo.planilla
        @uploader.key = "/uploads/#{UUIDTools::UUID.random_create}/planilla-#{@periodo.id}.xlsx"
        @uploader.success_action_redirect = periodo_url(@periodo)
	puts @uploader.inspect
        render :action => :subir_listado_materiales
      end
    elsif @periodo.status == 3
      render :action => :procesando
    end

  end

  # GET /periodos/new
  # GET /periodos/new.json
  def new
    @period = Periodo.new
    @period.time_start = nil
    @period.time_end = nil

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @period }
    end
  end

  # GET /periodos/1/edit
  def edit
    @period = Periodo.find(params[:id])
  end

  # POST /periodos
  # POST /periodos.json
  def create
    @period = Periodo.new(params[:periodo])


      if @period.save
        redirect_to periodo_url(@period), notice: 'Se ha creado un nuevo carro de compras'
      else
        render action: "new"

      end

  end

  # PUT /periodos/1
  # PUT /periodos/1.json
  def update
    @period = Periodo.find(params[:id])

    if @period.update_attributes(params[:periodo])
      redirect_to periodo_url(@period), notice: 'El periodo fue actualizado exitosamente.'
    else
      render action: 'edit'

    end

  end

  # DELETE /periodos/1
  # DELETE /periodos/1.json
  def destroy
    @period = Periodo.find(params[:id])
    @period.destroy

    respond_to do |format|
      format.html { redirect_to '/periodos' }
      format.json { head :no_content }
    end
  end
end

app/views/periodos/_estado_solicitudes_1.html.erb
<h2>Resumen de Solicitudes</h2>
<%= image_tag 'solicitud-sin-aprobar.png' %>
<table class="table table-striped table-bordered span8">
  <thead>
  <tr>
    <th>Región</th>
    <th>Creada</th>
    <th>Modificada</th>
    <th>Enviada</th>
  </tr>
  </thead>
  <tbody>
  <% for i in 1..16 %>
      <tr<%= ' class="info"'.html_safe if current_user.region == i %>>
        <td><%= i %></td>
        <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.CREADA ) %></td>
        <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.MODIFICADA ) %></td>
        <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.ENVIADA ) %></td>
      </tr>
  <% end %>


  <tr>
    <td><b>Total</b></td>
    <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.CREADA ) %></td>
    <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.MODIFICADA ) %></td>
    <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.ENVIADA ) %></td>


  </tr>
  </tbody>
</table>

app/views/periodos/_estado_solicitudes_2.html.erb
<h2>Resumen de Solicitudes</h2>
<div class="row">
  <div class="span7">
    <%= image_tag 'solicitud-sin-aprobar.png' %>
  </div>
  <table class="table table-striped table-bordered span5">
    <thead>
    <tr>
      <th>Región</th>
      <th>Creada</th>
      <th>Modificada</th>
      <th>Enviada</th>
    </tr>
    </thead>
    <tbody>
    <% for i in 1..16 %>
        <tr<%= ' class="info"'.html_safe if current_user.region == i %>>
          <td><%= i %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.CREADA ) %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.MODIFICADA ) %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.ENVIADA ) %></td>
        </tr>
    <% end %>


    <tr>
      <td><b>Total</b></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.CREADA ) %></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.MODIFICADA ) %></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.ENVIADA ) %></td>


    </tr>
    </tbody>
  </table>
</div>

app/views/periodos/_estado_solicitudes_3.html.erb
<h2>Resumen de Solicitudes</h2>
<div class="row">
  <div class="span7">
    <%= image_tag 'solicitud-con-aprobar.png' %>
  </div>
  <table class="table table-striped table-bordered span5">
    <thead>
    <tr>
      <th>Región</th>
      <th>Creada</th>
      <th>Modificada</th>
      <th>Enviada</th>
      <th>Con <br />comentarios</th>
      <th>Aprobada</th>
    </tr>
    </thead>
    <tbody>
    <% for i in 1..16 %>
        <tr<%= ' class="info"'.html_safe if current_user.region == i %>>
          <td><%= i %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.CREADA ) %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.MODIFICADA ) %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.ENVIADA ) %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.COMENTARIOS ) %></td>
          <td><%= Solicitud.count_by_region_estado_periodo(i,@periodo.id, Solicitud.APROBADA ) %></td>
        </tr>
    <% end %>


    <tr>
      <td><b>Total</b></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.CREADA ) %></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.MODIFICADA ) %></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.ENVIADA ) %></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.COMENTARIOS ) %></td>
      <td><%= Solicitud.count_by_estado_periodo(@periodo.id, Solicitud.APROBADA ) %></td>


    </tr>
    </tbody>
  </table>
</div>

app/views/periodos/_form.html.erb
<%= form_for(@period, :html => {:class => 'form-horizontal' }) do |f| %>
  <% if @period.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2>Los cambios no pudieron ser guardados, porque <%= (@period.errors.count == 1) ? 'se encontró 1 error.':"se encontraron #{@period.errors.count} errores" %>:</h2>

      <ul>
      <% @period.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="control-group">
      <%= f.label :nombre, 'Nombre', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :nombre %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :time_start, 'Fecha Inicio', :class => 'control-label' %>
      <div class="controls">
        <% if @period.time_start.nil? %>
             <%= f.text_field :time_start %>
        <% else %>
            <%= f.text_field :time_start, :value => @period.time_start.strftime('%d-%m-%Y') %>
        <% end %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :time_end, 'Fecha Término', :class => 'control-label' %>
      <div class="controls">
        <% if @period.time_end.nil? %>
            <%= f.text_field :time_end %>
        <% else %>
            <%= f.text_field :time_end, :value => @period.time_end.strftime('%d-%m-%Y') %>
        <% end %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :tipo, 'Tipo de carro de compra', :class => 'control-label' %>
      <div class="controls">
        <label class="radio">
          <%= f.radio_button(:tipo, 1 ) %>
          Sin autorización regional, jardín posee un propuesta y puede elegir cualquier material. Materiales pertenecen a una única categoría. (Excel sólo contiene una hoja: presupuestos)
        </label>
        <label class="radio">
          <%= f.radio_button(:tipo, 2 ) %>
          Sin autorización regional, jardín sólo puede elegir materiales que pertenecen a su nivel y fungibles. Materiales pertenecen a distintas categorías. (Excel contiene dos hojas: materiales y presupuestos)
        </label>
        <label class="radio">
          <%= f.radio_button(:tipo, 3 ) %>
          Cada solicitud debe ser autorizada por un administrador regional, jefes regionales sólo pueden mirar. Jardín no posee propuesta y sólo puede elegir materiales que pertenecen a su nivel. Materiales pertenecen a distintas categorías. (Excel contiene dos hojas: materiales y presupuestos)
        </label>


      </div>
    </div>

    <div class="control-group">
        <%= f.label :instrucciones, 'Instrucciones', :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :instrucciones, :class => 'redactor2', :rows => 40, :cols => 120 %>
        </div>
    </div>

    <div class="control-group">
      <%= f.label :aprobado, 'Aprobado', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :aprobado, :class => 'redactor2', :rows => 40, :cols => 120 %>
        <span class="help-block">
          Este es el encabezado del mensaje que se envía al jardín infantil una vez que su solicitud ha sido aceptada.
          <br />
          Junto con este mensaje se envía una copia de la solicitud.


        </span>
      </div>
    </div>


  <div class="field">


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/periodos/_header.html.erb
<h1>Administrar periodo de postulación #<%= @periodo.id %></h1>
<h2><%= @periodo.nombre %></h2>

app/views/periodos/_index.html.erb
<br />
<br />

<% if @periodos.size == 0 %>
    <div class="alert alert-info">
    <p>En este momento no existen periodos de compras activos.</p>
    </div>
<% else %>
    <p>Por favor seleccione el proceso de compras en el cual desea participar:</p>


    <table class="table">
      <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Fecha término</th>
        <th>Estado de mi solicitud</th>
        <th>Presupuesto Asignado</th>
        <th>Presupuesto Solicitado</th>
        <th></th>
      </tr>

      <% @periodos.each do |period| %>
          <tr>
            <td><%= period.id %> </td>
            <td><%= period.nombre %></td>
            <td><%= period.time_end.strftime("%d-%m-%Y") %></td>
            <td><%= link_to @current_user.jardin.solicitud(period.id).estado_nombre_usuario, @current_user.jardin.solicitud(period.id) unless @current_user.jardin.solicitud(period.id).nil? %></td>
            <td><%= number_to_currency(@current_user.jardin.presupuesto(period.id), :precision => 0) %></td>
            <td><%= (@current_user.jardin.solicitud(period.id).estado == Solicitud.ENVIADA)? number_to_currency(@current_user.jardin.solicitud(period.id).costo_total, :precision => 0):'$ 0' unless @current_user.jardin.solicitud(period.id).nil? %></td>
            <td><%= link_to 'Ver', @current_user.jardin.solicitud(period.id), :class => 'btn btn-primary' %></td>
          </tr>
      <% end %>
    </table>

<% end %>

app/views/periodos/_index_admin.html.erb
<h1>Listado de procesos de carros de compra</h1>

<% if current_user.isAdmin? %>

<ul>
  <li><%= link_to 'Nuevo proceso de carro de compra', new_periodo_path %></li>
  <li><%= link_to 'Administrar usuarios', usuarios_url %></li>
</ul>

<% end %>


<table class="table">
  <tr>
    <th>Id</th>
    <th>Nombre</th>
    <th>Fecha Inicio</th>
    <th>Fecha término</th>

    <th>Activo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @periodos.each do |period| %>
      <tr>
        <td><%= period.id %> </td>
        <td><%= period.nombre %></td>
        <td><%= period.time_start.strftime('%d-%m-%Y') %></td>
        <td><%= period.time_end.strftime('%d-%m-%Y') %></td>
        <td class='<%= "periodo-activo-#{period.activo?}" %>'>
          <%= content_tag(:i, '', :class => period.activo? ? 'icon-ok':'icon-remove') %>
        </td>
        <td><%= link_to 'Administrar', period, :class => 'btn btn-info' %></td>
        <td><%= link_to 'Editar', edit_periodo_path(period), :class => 'btn' if current_user.isAdmin? %></td>
        <td><%= link_to 'Eliminar', period, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-danger' if current_user.isAdmin? %></td>
      </tr>
  <% end %>
</table>

<br />

app/views/periodos/_tabla.html.erb
<table class="table" id="solicitudes" data-periodo="<%= @periodo.id %>" data-pendientes="<%= !@pendientes.nil? %>">
	<thead>
  <tr>
		<th>Estado</th>
		<th>Dir.Reg</th>
		<th>Glosa Comuna</th>
		<th>Código<br />Jardín</th>
		<th>Nombre Jardín</th>
		<th>Modalidad<br />Atención</th>
    <th>Total<br />Presupuesto</th>
    <th>Total<br />Solicitado</th>
<% if current_user.isAdmin? %>
	<th>Acciones</th>
<% else %>
	<th>Acción</th>
<% end %>
  </tr>
	</thead>
	<tbody>
	</tbody>

	<tfoot>
	    <tr>
	        <th>TOTAL</th>
	        <th></th>
	        <th></th>
	        <th></th>
	        <th></th>
	        <th></th>
	        <th style="text-align:center"></th>
			<th style="text-align:center"></th>
	    </tr>
	</tfoot>
	
</table>

app/views/periodos/edit.html.erb
<h1>Editar proceso de carro de compras. Id: #<%= @period.id %></h1>

<%= render 'form' %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periodos_path %>

app/views/periodos/index.html.erb
<% if current_user.isAdmin? or (current_user.region > 0 and current_user.jardin_codigo == 0)%>
    <%= render :partial => 'index_admin' %>
<% else %>
    <%= render :partial => 'index'  %>
<% end %>

app/views/periodos/new.html.erb
<h1>Nuevo proceso de carro de compras </h1>



<%= render 'form' %>

<%= link_to 'Back', periodos_path %>

app/views/periodos/procesando.html.erb
<%= render :partial => "header" %>

<div class="alert alert-info">
Estamos procesando la lista de jardines y materiales, por favor espera un momento...
</div>

<script>
  setTimeout('location.reload()',10000);
</script>

app/views/periodos/subir_listado_materiales.html.erb
<%= render :partial => 'header' %>

<br />

Para continuar es necesario que cargues una planilla en formato XLSX con el listado de materiales y
presupuestos para todos los jardines que estarán activos en este proceso de carro de compra.


<br /><br />

<%= direct_upload_form_for @uploader do |f| %>
    <%= f.file_field :planilla %>
    <%= f.submit 'Subir listado de materiales' %>
<% end %>