config/routes.rb
Integra::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'

  resources :jardines

  match 'materiales/modal/:id' => 'materiales#modal'
  match 'solicitudes/pendientes' => 'solicitudes#pendientes'
  resources :solicitudes, :only => :show

  match '/periodos/:periodo_id/materiales/upload' => 'materiales#upload'

  resources :periodos do
    resources :materiales
    resources :solicitudes, :except => [:show, :new]
  end

  resources :categorias
  match 'solicitudes/xls' => "solicitudes#xls"
  match 'solicitudes/:solicitud_id/aprobar' => 'solicitudes#aprobar'
  match 'solicitudes/:solicitud_id/rechazar' => 'solicitudes#rechazar'
  match 'solicitudes/new/:jardin_id' => "solicitudes#new"
  get 'jardines/:jardin/usuarios' => "usuarios#index"
  delete 'jardines/:jardin/usuarios' => "usuarios#destroy"
  match 'usuarios/upload' => 'usuarios#upload'
  get '/usuarios/:id/edit' => 'usuarios#edit'
  put '/usuarios/:id' => 'usuarios#update'
  get '/usuarios/:jardin_codigo/new' => 'usuarios#new'
  match '/usuarios/:jardin_codigo/edit' => 'usuarios#edit'
  post '/usuarios' => 'usuarios#create'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :sessions

  resources :usuarios


  root :to => 'periodos#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :color, :nombre
  has_many :materiales

  def self.buscar(input)
    @test ||= {}
    @test[input] ||= Categoria.where(:nombre => input).first
    @test[input] ||= Categoria.where(['lower(nombre) = ?',input.downcase]).first
    @test[input] ||= Categoria.where(['lower(nombre) = ?',input.downcase.gsub(/material /,'')]).first
    @test[input] ||= Categoria.where(['lower(nombre) = ?',input.downcase.gsub(/material /,'').singularize]).first
    @test[input] ||= Categoria.where(['nombre = ?',input.gsub(/MATERIAL /,'')]).first
    @test[input] ||= Categoria.where(['nombre = ?',input.gsub(/MATERIAL /,'').pluralize.upcase]).first
    return @test[input]
  end

end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  before_filter :require_valid_user
  
  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorias }
    end
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
    @categoria = Categoria.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/new
  # GET /categorias/new.json
  def new
    @categoria = Categoria.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categoria }
    end
  end

  # GET /categorias/1/edit
  def edit
    @categoria = Categoria.find(params[:id])
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(params[:categoria])

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to categorias_path, notice: 'Categoria was successfully created.' }
        format.json { render json: @categoria, status: :created, location: @categoria }
      else
        format.html { render action: "new" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorias/1
  # PUT /categorias/1.json
  def update
    @categoria = Categoria.find(params[:id])
    respond_to do |format|
      if @categoria.update_attributes(params[:categoria])
        format.html { redirect_to categorias_path, notice: 'Categoria was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria = Categoria.find(params[:id])
    @categoria.destroy

    respond_to do |format|
      format.html { redirect_to categorias_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/categorias/_form.html.erb
<br />
<%= form_for(@categoria,:html => {:class => "form-horizontal"}) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :nombre,:class => 'control-label' %>
		<div class="controls">
    <%= f.text_field :nombre %>
		</div>
  </div>
  <div class="control-group">
		<%= f.label :color,:class => 'control-label' %>
		<div class="controls">
			<div class="input-append color" data-color="<%= @categoria.color %>" data-color-format="rgb" id="cp3">
				<input type="text" name="categoria[color]" class="hide" value="" readonly >
				<span class="add-on"><i style="background-color: <%= @categoria.color %>"></i></span>
			</div>
		</div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
	$(function(){
		$('#cp3').colorpicker().on('changeColor', function(ev){
			
		})
	})
</script>

app/views/categorias/edit.html.erb
<h1>Editing categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @categoria %> |
<%= link_to 'Back', categorias_path %>

app/views/categorias/index.html.erb
<h1>Listing categorias</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
  </tr>

<% @categorias.each do |categoria| %>
  <tr>
    <td style="background-color: <%= categoria.color %>"><%= categoria.nombre %></td>
    <td><%= link_to 'Edit', edit_categoria_path(categoria) %></td>
    <td><%= link_to 'Destroy', categoria, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categoria', new_categoria_path %>

app/views/categorias/new.html.erb
<h1>New categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', categorias_path %>

app/views/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @categoria.nombre %>
</p>

<p>
  <b>Color:</b>
  <%= @categoria.color %>
</p>


<%= link_to 'Edit', edit_categoria_path(@categoria) %> |
<%= link_to 'Back', categorias_path %>