config/routes.rb
Integra::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'

  resources :jardines

  match 'materiales/modal/:id' => 'materiales#modal'
  match 'solicitudes/pendientes' => 'solicitudes#pendientes'
  resources :solicitudes, :only => :show

  match '/periodos/:periodo_id/materiales/upload' => 'materiales#upload'

  resources :periodos do
    resources :materiales
    resources :solicitudes, :except => [:show, :new]
  end

  resources :categorias
  match 'solicitudes/xls' => "solicitudes#xls"
  match 'solicitudes/:solicitud_id/aprobar' => 'solicitudes#aprobar'
  match 'solicitudes/:solicitud_id/rechazar' => 'solicitudes#rechazar'
  match 'solicitudes/new/:jardin_id' => "solicitudes#new"
  get 'jardines/:jardin/usuarios' => "usuarios#index"
  delete 'jardines/:jardin/usuarios' => "usuarios#destroy"
  match 'usuarios/upload' => 'usuarios#upload'
  get '/usuarios/:id/edit' => 'usuarios#edit'
  put '/usuarios/:id' => 'usuarios#update'
  get '/usuarios/:jardin_codigo/new' => 'usuarios#new'
  match '/usuarios/:jardin_codigo/edit' => 'usuarios#edit'
  post '/usuarios' => 'usuarios#create'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :sessions

  resources :usuarios


  root :to => 'periodos#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/jardines_controller.rb
class JardinesController < ApplicationController
   before_filter :admin_or_regional_permission
   before_filter :admin_permission, :only => [:destroy, :create, :edit]
  # GET /jardines
  # GET /jardines.json
  def index
    #@jardines = Jardin.find(:all, :conditions => ["activo = 1"], :order => "region, codigo")
    # @jardines = Solicitud.find(:all, :include => [:jardin], :conditions => ["periodo_id = #{PERIODO}"], :order => "jardin_id ASC")
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @jardines }
    # end
    redirect_to "/solicitudes"
  end

  # GET /jardines/1
  # GET /jardines/1.json
  def show
    @jardin = Jardin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jardin }
    end
  end

  # GET /jardines/new
  # GET /jardines/new.json
  def new
    @jardin = Jardin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jardin }
    end
  end

  # GET /jardines/1/edit
  def edit
    @jardin = Jardin.find(params[:id])
  end

  # POST /jardines
  # POST /jardines.json
  def create
    @jardin = Jardin.new(params[:jardin])
    @jardin.activo = 1
    respond_to do |format|
      if @jardin.save
        format.html { redirect_to "/periodos", notice: "Jardin #{@jardin.nombre} fue creado exitosamente." }
        format.json { render json: @jardin, status: :created, location: @jardin }
      else
        format.html { render action: "new" }
        format.json { render json: @jardin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jardines/1
  # PUT /jardines/1.json
  def update
    @jardin = Jardin.find(params[:id])

    respond_to do |format|
      if @jardin.update_attributes(params[:jardin])
        format.html { redirect_to root_url, notice: "Jardin #{@jardin.nombre} fue actualizado exitosamente." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jardin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jardines/1
  # DELETE /jardines/1.json
  #def destroy
  #  @jardin = Jardin.find(params[:id])
  #  ss = Solicitud.find(:all, :conditions => ["jardin_id = ?", @jardin.codigo])
  #  for s in ss
  #    s.destroy unless s.nil?
  #  end
  #  @jardin.destroy
  #
  #  respond_to do |format|
  #    format.html { redirect_to "/solicitudes" }
  #    format.json { head :no_content }
  #  end
  #end
end

app/helpers/jardines_helper.rb
module JardinesHelper
end

app/views/jardines/_form.html.erb
<%= form_for(@jardin, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @jardin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jardin.errors.count, "error") %> prohibited this jardin from being saved:</h2>

      <ul>
      <% @jardin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :codigo, nil, :class => 'control-label'  %>
	<div class="controls">
    <%= f.number_field :codigo %>
	</div>
  </div>
  <div class="control-group">
    <%= f.label :region, nil, :class => 'control-label' %>
	<div class="controls">
    <%= f.number_field :region %>
	</div>
  </div>
  <div class="control-group">
    <%= f.label :comuna, nil, :class => 'control-label'  %>
	<div class="controls">
    <%= f.text_field :comuna %>
	</div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, nil, :class => 'control-label'  %>
	<div class="controls">
    <%= f.text_field :nombre %>
	</div>
  </div>
  <div class="control-group">
    <%= f.label :modalidadAtencion, nil, :class => 'control-label'  %>
	<div class="controls">
    <%= f.text_field :modalidadAtencion %>
	</div>
  </div>

  <div class="control-group">
		<%= f.label :niveles, 'Niveles', :class => 'control-label' %>
	<div class="controls">
		<% for i in NIVELES %>
          <label class="checkbox">
			<%= check_box_tag "jardin[nivel[#{i}]]", 1, @jardin.has_nivel(i) %>
			<%= i %>
          </label>
		<% end %>
	</div>
  </div>
  <div class="control-group">
	<div class="controls">
    <%= f.submit :class => "btn btn-primary" %>
	</div>
  </div>
<% end %>

app/views/jardines/edit.html.erb
<h1>Administración</h1>

<%= render :partial => 'solicitudes/navegation', :locals => {:active => 3} %>


<h2>Modificar jardín infantil</h2>
<%= render 'form' %>


<%= link_to 'Salir sin guardar cambios', root_url, :class => "btn btn-info" %>
<% if current_user.isAdmin? %>
<%= link_to 'Listado de usuarios con acceso a este jardín', "/jardines/#{@jardin.codigo}/usuarios", :class => "btn btn-info" %>
<%# link_to 'Eliminar este jardín', @jardin, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %>
<% end %>

app/views/jardines/index.html.erb
<h1>Listado de jardines</h1>

<%= render :partial => 'solicitudes/navegation', :locals => {:active => 3} %>

<ul class="nav nav-list">
<li class="nav-header">Jardines</li>
<li><%= link_to '<i class="icon-plus"></i> Nuevo Jardín Infantil'.html_safe, new_jardin_path %></li>
</ul>

<table class="table">
  <tr>
    <th>Codigo</th>
    <th>Región</th>
    <th>Comuna</th>
    <th>Nombre</th>
	<th>Niveles</th>
    <th>Presupuesto</th>
    <th></th>
    <th></th>
  </tr>

<% @jardines.each do |s| %>
  <tr>
    <td><%= s.jardin_id %></td>
    <td><%= s.jardin.region %></td>
    <td><%= s.jardin.comuna %></td>
    <td><%= s.jardin.nombre %></td>
	<td><%= s.jardin.niveles.join(",") %></td>
    <td><%= number_to_currency(s.presupuesto, {:precision => 0,:delimiter => '.'} ) %></td>
    <td><%= link_to 'Modificar Jardin', edit_jardin_path(s.jardin), :class => "btn" %></td>
	<td><%= link_to 'Modificar usuarios', "/jardines/#{s.jardin_id}/usuarios", :class => "btn" %></td>
    <td><%= link_to 'Eliminar', s.jardin, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

app/views/jardines/new.html.erb
<h1>Nuevo jardin</h1>

<%= render 'form' %>

<%= link_to 'Back', jardines_path %>

app/views/jardines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @jardin.codigo %>
</p>

<p>
  <b>Region:</b>
  <%= @jardin.region %>
</p>

<p>
  <b>Comuna:</b>
  <%= @jardin.comuna %>
</p>

<p>
  <b>Nombre:</b>
  <%= @jardin.nombre %>
</p>

<p>
  <b>Modalidadatencion:</b>
  <%= @jardin.modalidadAtencion %>
</p>

<p>
  <b>Presupuesto:</b>
  <%= @jardin.presupuesto %>
</p>


<%= link_to 'Edit', edit_jardin_path(@jardin) %> |
<%= link_to 'Back', jardines_path %>