config/routes.rb
Integra::Application.routes.draw do


  mount RedactorRails::Engine => '/redactor_rails'

  resources :jardines

  match 'materiales/modal/:id' => 'materiales#modal'
  match 'solicitudes/pendientes' => 'solicitudes#pendientes'
  resources :solicitudes, :only => :show

  match '/periodos/:periodo_id/materiales/upload' => 'materiales#upload'

  resources :periodos do
    resources :materiales
    resources :solicitudes, :except => [:show, :new]
  end

  resources :categorias
  match 'solicitudes/xls' => "solicitudes#xls"
  match 'solicitudes/:solicitud_id/aprobar' => 'solicitudes#aprobar'
  match 'solicitudes/:solicitud_id/rechazar' => 'solicitudes#rechazar'
  match 'solicitudes/new/:jardin_id' => "solicitudes#new"
  get 'jardines/:jardin/usuarios' => "usuarios#index"
  delete 'jardines/:jardin/usuarios' => "usuarios#destroy"
  match 'usuarios/upload' => 'usuarios#upload'
  get '/usuarios/:id/edit' => 'usuarios#edit'
  put '/usuarios/:id' => 'usuarios#update'
  get '/usuarios/:jardin_codigo/new' => 'usuarios#new'
  match '/usuarios/:jardin_codigo/edit' => 'usuarios#edit'
  post '/usuarios' => 'usuarios#create'
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :sessions

  resources :usuarios


  root :to => 'periodos#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_secure_password
  has_many :solicitudes, :class_name => "Solicitud"
  belongs_to :jardin, :foreign_key => "jardin_codigo", :primary_key => "codigo"
  attr_accessible :username,:nombre, :jardin_id, :region, :nombre,:password, :password_confirmation
  
  validates_uniqueness_of :username
  validates_presence_of :username
  before_validation :username_must_not_be_zero

  def username_must_not_be_zero
    self.username = self.username.strip
    return false if self.username.to_s == '0'
  end

  # attr_accessible :title, :body
  
  def isAdmin?
    return self.admin == 1
  end
  
  def username=(t)
      unless t.nil? or t.to_s.empty?
      write_attribute('username',t.to_s.split("-")[0].gsub(".",""))
    end
  end

  def self.actualizar_usuarios(file)
    input = nil
    begin
      input = Roo::Excelx.new(file)
    rescue TypeError
      begin
        input = Roo::Excel.new(file)
      rescue TypeError
        render :text => "formato no reconocido. Planilla debe venir en formato XLSX"
        return
      end
    end

    Usuario.connection.execute('UPDATE usuarios set valido = false, autoriza = false where admin = 0')
    for i in 2..input.last_row
      region = input.cell(i,'A').to_i
      codigo = input.cell(i,'D').to_i
      nombre = input.cell(i,'I')
      username = input.cell(i,'G').to_i.to_s
      puts "#{username} -> #{codigo}"


      jardin = Jardin.find_by_codigo(codigo)
      if jardin.nil?
        jardin = Jardin.new
        jardin.nombre = input.cell(i,'E')
        jardin.codigo = codigo
        jardin.region = region
        jardin.comuna = input.cell(i,'C')
        jardin.modalidad_atencion = input.cell(i,'F')
        jardin.save!
      end

      usuario = Usuario.where(:username => username).first
      if usuario.nil?
        usuario = Usuario.new
        usuario.username = username
        if usuario.username.length > 6
          usuario.password = usuario.username[0,4]
        else
          usuario.password = usuario.username
        end
      end
      usuario.nombre = nombre
      usuario.jardin_codigo = codigo
      usuario.region = region
      usuario.valido = true
      usuario.save!

    end
    hojas = input.sheets

    puts "usuarios regionales"
    if hojas.size > 1
      for i in 2..input.last_row(hojas[1])
        region = input.cell(i,'A',hojas[1]).to_i
        username = input.cell(i,'D',hojas[1]).to_i.to_s
        nombre = input.cell(i,'H',hojas[1])

        usuario = Usuario.where(:username => username).first
        if usuario.nil?
          puts "creando #{username}"
          usuario = Usuario.new
          usuario.username = username
          usuario.password = usuario.username[0,4]
        else
          puts "actualizando #{username}"
        end
        usuario.email = input.cell(i,'L',hojas[1])
        usuario.nombre = nombre
        usuario.region = region
        usuario.valido = true
        usuario.autoriza = (input.cell(i,'M',hojas[1]) == 'SI')
        usuario.save!
      end
    end
  end

  def self.usuario_job
    #Launchbg.start("bundle exec rake --trace environment 'integra:procesar_usuarios'")
    file = Carro.first.usuarios.to_s
    @carro = Carro.first
    begin
      Usuario.transaction do
        Usuario.actualizar_usuarios(file)
      end
      @carro.usuarios_status = 0
      @carro.save!
    rescue
      @carro.usuarios_status = 2
      @carro.save!
    end
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
   before_filter :admin_permission

  # GET /usuarios
  # GET /usuarios.json
  def index
    @carro = Carro.first
    if params[:key]
      @uploader = @carro.usuarios
      @uploader.key = params[:key]
      @carro.usuarios_status = 1
      @carro.save!
      UsuarioJob.new.async.perform()

    end
    if @carro.usuarios_status == 1
      render :action => :usuarios_wait
      return
    end


    if (params[:jardin].to_i == 0)
      @usuarios = Usuario.all
      render :action => 'index_usuarios'
    else
      @jardin = Jardin.find_by_codigo(params[:jardin])
      @usuarios = Usuario.where(['jardin_codigo = ? OR (region > 0 and region = ?) and valido = ?', @jardin.codigo,@jardin.region,true]).order('jardin_codigo DESC, nombre ASC').all
      if (!current_user.isAdmin? and current_user.region.to_i != @jardin.region.to_i)
          redirect_to root_url, :alert => 'permiso denegado'
      else
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @usuarios }
        end
      end
    end
  end

  def upload
    @carro = Carro.first
    @uploader = Carro.first.usuarios
    @uploader.key = "/uploads/#{UUIDTools::UUID.random_create}/usuarios.xlsx"
    @uploader.success_action_redirect = usuarios_url
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new
    @usuario.jardin_id = params[:jardin_codigo]
    @jardin = Jardin.find_by_codigo(params[:jardin_codigo])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])
    @jardin = Jardin.find_by_codigo(@usuario.jardin_id)
    respond_to do |format|
      if @usuario.save
        format.html {
          if @usuario.isAdmin?
            redirect_to "/solicitudes", notice: "Usuario fue creado exitosamente."
          else
            redirect_to "/jardines/#{@usuario.jardin_id}/usuarios", notice: "Usuario fue creado exitosamente."
          end}
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :username, nil, :class => 'control-label' %>
	<div class="controls">
    <%= f.text_field :username %>
	</div>
  </div>

  <div class="control-group">
    <%= f.label :password, nil, :class => 'control-label' %>
	<div class="controls">
    <%= f.password_field :password %>
	</div>
  </div>

  <div class="control-group">
    <%= f.label :password_confirmation, "Confirmación de password", :class => 'control-label' %>
	<div class="controls">
    <%= f.password_field :password_confirmation %>
	</div>
  </div>

  <div class="control-group">
    <%= f.label :nombre, nil, :class => 'control-label' %>
	<div class="controls">
    <%= f.text_field :nombre %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :jardin_id, nil, :class => 'control-label' %>
	<div class="controls">    
	<%= f.number_field :jardin_id %>
  	</div>
  </div>

  <div class="control-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Administración</h1>

<%= render :partial => 'solicitudes/navegation', :locals => {:active => 5} %>


<h1>Modificar usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', "/jardines/#{@usuario.jardin_id}/usuarios" %>

app/views/usuarios/index.html.erb
<h1>Administración</h1>

<%= render :partial => 'solicitudes/navegation', :locals => {:active => 5} %>



<h2>Usuarios para jardín: <%= @jardin.nombre %></h2>


<table class="table">
  <tr>
    <th>Username</th>
    <th>Nombre</th>
    <th>Jardin</th>
	<th>Administrador<br />Regional</th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.username %></td>
    <td><%= usuario.nombre %></td>
    <td><%= usuario.jardin_codigo %></td>
	<td><%= usuario.region?? '<i class="icon-ok"></i>'.html_safe : '<i class="icon-remove"></i>'.html_safe %></td>
    <td><%= link_to 'Modificar', "/usuarios/#{usuario.id}/edit" %></td>
    <td><%= link_to 'Eliminar', "/usuarios/#{usuario.id}", confirm: 'Are you sure?', method: :delete %>
<%# link_to 'Eliminar', usuario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/usuarios/index_usuarios.html.erb
<h1>Administración</h1>

<% if @carro.usuarios_status == 2 %>
  <div class="alert alert-error">Ocurrió un error al procesar la última planilla de usuarios</div>

<% end %>

<%= render :partial => 'solicitudes/navegation', :locals => {:active => 5} %>

<%= link_to 'Subir planilla con usuarios', :action => :upload %>
<br />

app/views/usuarios/new.html.erb
<h1>Administración</h1>

<%= render :partial => 'solicitudes/navegation', :locals => {:active => 6} %>


<h2>Nuevo usuario para jardin: <%= @jardin.nombre %></h2>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @usuario.username %>
</p>

<p>
  <b>Nombre:</b>
  <%= @usuario.nombre %>
</p>

<p>
  <b>Jardin:</b>
  <%= @usuario.jardin_id %>
</p>

<p>
  <b>Region:</b>
  <%= @usuario.region %>
</p>

<p>
  <b>Admin:</b>
  <%= @usuario.admin %>
</p>


<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/upload.html.erb
<h1>Administración</h1>

<%= render :partial => 'solicitudes/navegation', :locals => {:active => 5} %>

<br />
<% if @carro.usuarios_status == 2 %>
  <div class="alert alert-error">Ocurrió un error al procesar la última planilla de usuarios</div>
<% end %>

<%= direct_upload_form_for @uploader do |f| %>
    <%= f.file_field :usuarios %>
    <%= f.submit %>
<% end %>

app/views/usuarios/usuarios_wait.html.erb
<br /><br />
<div class="alert alert-info">
Estamos procesando la lista de usuarios, por favor espera un momento...
</div>


<script>
    setTimeout('location.replace("/usuarios")',10000);
</script>